/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathsIndexRouteImport } from './routes/paths.index'
import { Route as PathsNewRouteImport } from './routes/paths.new'
import { Route as PathSlugRouteImport } from './routes/path.$slug'
import { Route as GuideIdRouteImport } from './routes/guide.$id'
import { Route as CreatorHandleRouteImport } from './routes/creator.$handle'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsIndexRoute = PathsIndexRouteImport.update({
  id: '/paths/',
  path: '/paths/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsNewRoute = PathsNewRouteImport.update({
  id: '/paths/new',
  path: '/paths/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PathSlugRoute = PathSlugRouteImport.update({
  id: '/path/$slug',
  path: '/path/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideIdRoute = GuideIdRouteImport.update({
  id: '/guide/$id',
  path: '/guide/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorHandleRoute = CreatorHandleRouteImport.update({
  id: '/creator/$handle',
  path: '/creator/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/creator/$handle': typeof CreatorHandleRoute
  '/guide/$id': typeof GuideIdRoute
  '/path/$slug': typeof PathSlugRoute
  '/paths/new': typeof PathsNewRoute
  '/paths/': typeof PathsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/creator/$handle': typeof CreatorHandleRoute
  '/guide/$id': typeof GuideIdRoute
  '/path/$slug': typeof PathSlugRoute
  '/paths/new': typeof PathsNewRoute
  '/paths': typeof PathsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/creator/$handle': typeof CreatorHandleRoute
  '/guide/$id': typeof GuideIdRoute
  '/path/$slug': typeof PathSlugRoute
  '/paths/new': typeof PathsNewRoute
  '/paths/': typeof PathsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/search'
    | '/category/$slug'
    | '/creator/$handle'
    | '/guide/$id'
    | '/path/$slug'
    | '/paths/new'
    | '/paths/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/search'
    | '/category/$slug'
    | '/creator/$handle'
    | '/guide/$id'
    | '/path/$slug'
    | '/paths/new'
    | '/paths'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/search'
    | '/category/$slug'
    | '/creator/$handle'
    | '/guide/$id'
    | '/path/$slug'
    | '/paths/new'
    | '/paths/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CreatorHandleRoute: typeof CreatorHandleRoute
  GuideIdRoute: typeof GuideIdRoute
  PathSlugRoute: typeof PathSlugRoute
  PathsNewRoute: typeof PathsNewRoute
  PathsIndexRoute: typeof PathsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/': {
      id: '/paths/'
      path: '/paths'
      fullPath: '/paths/'
      preLoaderRoute: typeof PathsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/new': {
      id: '/paths/new'
      path: '/paths/new'
      fullPath: '/paths/new'
      preLoaderRoute: typeof PathsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/$slug': {
      id: '/path/$slug'
      path: '/path/$slug'
      fullPath: '/path/$slug'
      preLoaderRoute: typeof PathSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$id': {
      id: '/guide/$id'
      path: '/guide/$id'
      fullPath: '/guide/$id'
      preLoaderRoute: typeof GuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$handle': {
      id: '/creator/$handle'
      path: '/creator/$handle'
      fullPath: '/creator/$handle'
      preLoaderRoute: typeof CreatorHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  CategorySlugRoute: CategorySlugRoute,
  CreatorHandleRoute: CreatorHandleRoute,
  GuideIdRoute: GuideIdRoute,
  PathSlugRoute: PathSlugRoute,
  PathsNewRoute: PathsNewRoute,
  PathsIndexRoute: PathsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
